// debugger/src/App.vue
<template>
  <div class="h-full flex">
    <div class="p-4 bg-base-200 flex flex-col gap-2 w-80">
      <p class="text-xl mb-2">Nebula</p>
      <p class="text-lg">Data Source</p>
      <div>
        <base-radio-button label="Server" @click="source_type = 'server'" :checked="source_type === 'server'" />
        <base-radio-button label="Text" @click="source_type = 'text'" :checked="source_type === 'text'" />
      </div>
      <template v-if="source_type === 'text'">
        <BaseTextField v-model="textData" multiline @input="onStart" placeholder="Paste data in here..." />
      </template>
      <template v-else-if="source_type === 'server'">
        <p class="text-sm">Stream Host</p>
        <BaseTextField placeholder="127.0.0.1" v-model="host" />
        <p class="text-sm">Camera Server Port</p>
        <BaseTextField placeholder=":8000" v-model="camera_port" />
        <p class="text-sm">Controller Port</p>
        <BaseTextField placeholder=":1337" v-model="controller_port" />
      </template>
      <BaseButton @click="() => started ? onStop() : onStart()">{{ started ? 'Stop' : 'Start' }}</BaseButton>
    </div>
    <div class="flex flex-col flex-1">
      <div class="flex items-center gap-4 p-3 bg-base-200">
        <div class="flex">
          <BaseButton class="btn-sm" @click="source?.back()">
            <i-mdi-arrow-left />
          </BaseButton>
          <BaseButton class="btn-sm" @click="source?.next()">
            <i-mdi-arrow-right />
          </BaseButton>
        </div>
        <p class="text-lg text-gray-300">Viewer</p>
        <input @input="source?.goTo($event.target.value)" type="range" min="0" :max="frame_count" :value="frame_number"
          class="range range-xs" />
        <BaseButton class="btn-circle btn-sm text-lg" @click="onClear">
          <i-mdi:delete-empty-outline />
        </BaseButton>
      </div>
      <base-tabs class="w-full bg-base-300" :items="tabs" v-model="active_tab" />
      <div class="w-full relative flex-1 flex-col flex">
        <div class="absolute bottom-0 border-4 font-mono text-primary-content border-4" :style="{
          color: '#ffff'
        }">
          <div class="px-2 py-1 w-full" :style="{ backgroundColor: 'rgb(91, 206, 250)' }">{{ frame_number }}</div>
          <div class="px-2 py-1 bg-secondary w-full" :style="{ backgroundColor: 'rgb(245, 169, 184)' }">
            {{
              frame_count
            }}
          </div>
        </div>
        <img class="h-full" v-if="active_tab === 'Camera'" :src="`http://${host}${camera_port}/stream.mjpg`" />
        <LineView v-if="current_frame && active_tab === 'Line'" :data="current_frame" />
      </div>
      <div class="text-xs overflow-y-auto bg-base-200 font-mono h-40 flex border-t-2 gap-2">
        <div class="w-1/4 p-4">
          {{ config }}
        </div>
        <div class="flex-1 border-l-2 p-4">
          {{ current_frame }}
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onKeyStroke, useLocalStorage } from '@vueuse/core';
import debounce from 'lodash.debounce';
import { ref } from 'vue';
import BaseButton from './components/BaseButton.vue';
import BaseRadioButton from './components/BaseRadioButton.vue';
import BaseTabs from './components/BaseTabs.vue';
import BaseTextField from './components/BaseTextField.vue';
import LineView from './LineView.vue';
import { Config, DataObject, DataSource, ServerSource, TextSource } from './logic/dataSources';

const host = useLocalStorage("host", "127.0.0.1")
const camera_port = useLocalStorage("camera_port", ref(":8000"))
const controller_port = useLocalStorage("controller_port", ref(":7272"))
const source_type = ref<'server' | 'text'>('server')
const tabs = ['Line', 'Camera']
const active_tab = ref(tabs[0])

let source = ref<DataSource | undefined>(undefined)

const started = ref(false)
const textData = ref("");
const current_frame = ref<DataObject | undefined>(undefined);
const frame_count = ref(0);
const frame_number = ref(0);
const config = ref<Config>()

const onStart = async () => {
  started.value = true
  try {
    if (source_type.value === 'text') {
      source.value = new TextSource(textData.value)
    } else {
      source.value = new ServerSource(`${host.value}${controller_port.value}`)
    }
  } catch (e) {
    console.error(e)
  }
  config.value = await source.value?.currentConfig();
  source.value?.onFrame(debounce(frame => {
    current_frame.value = frame
    frame_count.value = source.value?.numFrames() ?? 0
    frame_number.value = source.value?.currentFrame() ?? 0
  }, 20, {
    maxWait: 20
  }))
  source.value?.next();
};

const onStop = () => {
  started.value = false;
  source.value?.stop();
}

const onClear = () => {
  source.value?.clear();
}

onKeyStroke('ArrowLeft', () => source.value?.back());
onKeyStroke('ArrowRight', () => source.value?.next());
</script>

<style scoped lang="postcss">
</style>

// debugger/src/App.tsx
import { Component, createSignal, Match, Show, Switch } from "solid-js";
import ArrowLeft from "~icons/mdi/arrow-left";
import ArrowRight from "~icons/mdi/arrow-right";
import { CameraView } from "./CameraView";
import { ShimmerButton } from "./components/Base/BaseButton";
import { BaseInput } from "./components/Base/BaseInput";
import { BaseRadioButton } from "./components/Base/BaseRadioButton";
import { BaseSlider } from "./components/Base/BaseSlider";
import { Label } from "./components/Base/Label";
import { Split } from "./components/Base/Split";
import {
  DataObject,
  DataSource,
  ServerSource,
  TextSource,
} from "./data_sources";
import { createStoredSignal } from "./helpers/createStoredSignal";
import { RobotView } from "./RobotView";

enum View {
  Robot,
  Camera,
  Config,
}

const App: Component = () => {
  const [serverAddress, setServerAddress] = createStoredSignal(
    "0.0.0.0:7272",
    "serverAddress"
  );
  const [cameraAddress, setCameraAddress] = createStoredSignal(
    "0.0.0.0:7272",
    "cameraAddress"
  );
  const [textData, setTextData] = createStoredSignal("", "textData");
  const [sourceType, setSourceType] = createStoredSignal<"server" | "text">(
    "server",
    "sourceType"
  );
  const [view, setView] = createStoredSignal<View>(View.Robot, "view");
  const [started, setStarted] = createSignal(false);
  const [frameCount, setFrameCount] = createSignal(0);
  const [frameIndex, setFrameIndex] = createSignal(0);
  const [currentFrame, setCurrentFrame] = createSignal<DataObject | undefined>(
    undefined
  );

  let source: DataSource | undefined = undefined;

  const onClick = () => {
    setStarted(!started());
    if (started()) {
      switch (sourceType()) {
        case "server":
          source = new ServerSource(serverAddress());
          break;
        case "text":
          source = new TextSource(textData());
      }
      source!.onFrame((frame) => {
        setFrameCount(source!.numFrames() - 1);
        setFrameIndex(source!.currentFrame());
        setCurrentFrame(frame);
      });
      source.next();
    } else {
      source!.stop();
    }
  };

  return (
    <div class="flex h-full">
      <div class="w-72 bg-dark-600 h-full overflow-auto">
        <div class="px-4 py-4 flex flex-col gap-4">
          <a class="hover:underline underline-offset-4">Nebula</a>
          <BaseRadioButton
            label="Server"
            name="source"
            checked={sourceType() === "server"}
            onClick={() => setSourceType("server")}
          />
          <BaseRadioButton
            label="Text Input"
            name="source"
            checked={sourceType() === "text"}
            onClick={() => setSourceType("text")}
          />
          <Switch fallback={<p>Select a Data Source</p>}>
            <Match when={sourceType() === "server"}>
              <Label>Server Address</Label>
              <BaseInput
                label="0.0.0.0:7272"
                onInput={(ev) => setServerAddress(ev.currentTarget.value)}
                value={serverAddress()}
              />
              <Label>Camera Address</Label>
              <BaseInput
                label="0.0.0.0:7273"
                onInput={(ev) => setCameraAddress(ev.currentTarget.value)}
                value={cameraAddress()}
              />
            </Match>
            <Match when={sourceType() === "text"}>
              <Label>Text Input</Label>
              <BaseInput
                textarea
                onInput={(ev) => setTextData(ev.currentTarget.value)}
                value={textData()}
              />
            </Match>
          </Switch>
          <ShimmerButton onClick={onClick}>
            {started() ? "Stop" : "Start"}
          </ShimmerButton>
        </div>
      </div>
      <Show
        when={currentFrame()}
        fallback={<div class="flex-1 p-3">Press start to begin monitoring</div>}
      >
        <div class="flex-1 flex-col flex">
          <div class="bg-dark-300 p-2 flex gap-2">
            <ShimmerButton onClick={() => source?.next()}>
              <ArrowLeft />
            </ShimmerButton>
            <ShimmerButton onClick={() => source?.back()}>
              <ArrowRight />
            </ShimmerButton>
            <BaseSlider
              class="w-full"
              showValue
              label="Frame No."
              min={0}
              max={frameCount()}
              step={1}
              value={frameIndex()}
              onInput={(ev) => {
                source?.goTo(ev.currentTarget.valueAsNumber);
                setFrameIndex(ev.currentTarget.valueAsNumber);
              }}
            />
          </div>
          <Split
            direction="vertical"
            gutterSize={5}
            sizes={[70, 30]}
            gutterClass="bg-dark-800 h-1 cursor-ns-resize active:bg-blue-500 transition duration-200"
          >
            <div class="relative">
              <Switch>
                <Match when={view() === View.Robot}>
                  <RobotView frame={currentFrame()!} />
                </Match>
                <Match when={view() === View.Camera}>
                  <CameraView host={cameraAddress()} />
                </Match>
              </Switch>
              <div class="absolute top-0 right-0 flex flex-col gap-2 bg-black/90 p-3 rounded-bl-4">
                <BaseRadioButton
                  checked={view() === View.Robot}
                  onClick={() => setView(View.Robot)}
                  label="Robot View"
                  name="view"
                />
                <BaseRadioButton
                  checked={view() === View.Camera}
                  onClick={() => setView(View.Camera)}
                  label="Camera View"
                  name="view"
                />
              </div>
            </div>
            <div class="overflow-auto whitespace-pre-wrap break-all h-full w-full">
              <p>{JSON.stringify(currentFrame())}</p>
            </div>
          </Split>
        </div>
      </Show>
    </div>
  );
};

export default App;
